// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuicktypeProperty;
//
//    var propertyData = PropertyData.FromJson(jsonString);

namespace QuicktypeProperty
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class PropertyData
    {
        [JsonProperty("objectid")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Objectid { get; set; }

        [JsonProperty("work_type")]
        public string WorkType { get; set; }

        [JsonProperty("work_subtype")]
        public string WorkSubtype { get; set; }

        [JsonProperty("display_agency")]
        public string DisplayAgency { get; set; }

        [JsonProperty("number_key")]
        public string NumberKey { get; set; }

        [JsonProperty("comp_type")]
        public string CompType { get; set; }

        [JsonProperty("comp_type_desc")]
        public string CompTypeDesc { get; set; }

        [JsonProperty("sub_type")]
        public string SubType { get; set; }

        [JsonProperty("sub_type_desc")]
        public string SubTypeDesc { get; set; }

        [JsonProperty("entered_date")]
        public DateTimeOffset EnteredDate { get; set; }

        [JsonProperty("data_status")]
        public string DataStatus { get; set; }

        [JsonProperty("data_status_display")]
        public string DataStatusDisplay { get; set; }

        [JsonProperty("status_class")]
        public string StatusClass { get; set; }

        [JsonProperty("street_no")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long StreetNo { get; set; }

        [JsonProperty("street_name")]
        public string StreetName { get; set; }

        [JsonProperty("city_id")]
        public string CityId { get; set; }

        [JsonProperty("x_coord")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long XCoord { get; set; }

        [JsonProperty("y_coord")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long YCoord { get; set; }

        [JsonProperty("wfdb")]
        public string Wfdb { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("last_updated")]
        public DateTimeOffset LastUpdated { get; set; }

        [JsonProperty("yn_activity_report")]
        public string YnActivityReport { get; set; }

        [JsonProperty("latitude")]
        public string Latitude { get; set; }

        [JsonProperty("longitude")]
        public string Longitude { get; set; }

        [JsonProperty("neighborhood")]
        public string Neighborhood { get; set; }

        [JsonProperty("uniqueid", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? Uniqueid { get; set; }
    }

    public partial class PropertyData
    {
        public static List<PropertyData> FromJson(string json) => JsonConvert.DeserializeObject<List<PropertyData>>(json, QuicktypeProperty.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<PropertyData> self) => JsonConvert.SerializeObject(self, QuicktypeProperty.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}